{
 "title": "Logs",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "container", "label": "Container", "query": "label_values(container)" },
   { "name": "level", "label": "Level", "query": "label_values(level)" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=~\"${container:regex}\", level=~\"${level}\"} | json |~ \"(?i)${search}\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of errors",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=~\"${container:regex}\", level=\"ERROR\"} | json |~ \"(?i)${search}\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"${container:regex}\", level=~\"${level}\"} | json |~ \"(?i)${search}\" | line_format \"{{.timestamp}} {{.trace_id}} {{.level}} {{.container}} — {{.message}}\""
    }
   ]
  }
 ]
}